name: Make Inventory
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install screenshot-glb
      run: npm install --save @shopify/screenshot-glb

    - name: Take screenshots
      run: |
        chmod +x take_screenshots.sh
        ./take_screenshots.sh

    - name: Update READMEs
      run: |
        chmod +x update_readmes.sh
        ./update_readmes.sh > README.md

    - name: Commit changes
      run: |
        git config --global user.name "madjin"
        git config --global user.email "32600939+madjin@users.noreply.github.com"
        git add .
        git commit -m "Update READMEs"
        git push
